version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - ezh
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.20
    - 1.17.21
    - 1.17.23
    - 1.17.24
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.3
    - 1.17.30
    - 1.17.31
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.37
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.42
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.59
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: dependency-injector
    versions:
    - 4.11.3
    - 4.13.0
    - 4.14.0
    - 4.16.0
    - 4.17.0
    - 4.20.1
    - 4.20.2
    - 4.23.0
    - 4.23.2
    - 4.23.5
    - 4.24.0
    - 4.25.1
    - 4.26.0
    - 4.28.1
    - 4.29.0
    - 4.29.1
    - 4.29.2
    - 4.31.0
    - 4.31.1
    - 4.31.2
    - 4.32.0
    - 4.32.1
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: pydoc-markdown
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-console-scripts
    versions:
    - 1.1.0
