repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.0.0
    hooks:
      - id: add-trailing-comma
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: ["--ignore=E501,W503"]
        language_version: python3
        additional_dependencies: [
          flake8-2020, # flake8 plugin which checks for misuse of `sys.version` or `sys.version_info`
          flake8-blind-except, # A flake8 extension that checks for blind except: statements
          flake8-bugbear, # A plugin for flake8 finding likely bugs and design problems in your program.
          #                 # Contains warnings that don't belong in pyflakes and pycodestyle.
          flake8-builtins, # Check for python builtins being used as variables or parameters.
          flake8-comprehensions, # It helps you write a better list/set/dict comprehensions.
          flake8-copyright, # Adds copyright checks to flake8
          flake8-deprecated, # Warns about deprecated method calls.
          dlint, # Dlint is a tool for encouraging best coding practices and helping ensure we're writing secure Python code.
          # flake8-docstrings, # Extension for flake8 which uses pydocstyle to check docstrings
          flake8-eradicate, # Flake8 plugin to find commented out code
          flake8-license,
          # pandas-vet, # A Flake8 plugin that provides opinionated linting for pandas code
          flake8-pytest, # pytest assert checker plugin for flake8
          flake8-variables-names, # flake8 extension that helps to make more readable variables names
          pep8-naming, # Check PEP-8 naming conventions, plugin for flake8
          flake8-copyright,
          flake8-ownership,
          flake8-docstrings,
          flake8-rst-docstrings,
          flake8-rst,
        ]
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: ['--fix=no']
