language: python
cache: pip

install:
  - pip install codecov tox
  - git clone https://github.com/junegunn/fzf/
  - fzf/install --bin
  - sudo ln -s $PWD/fzf/bin/fzf /usr/bin
jobs:
  include:
    - stage: test
      env: TOXENV=py35 CLOUDSELECT_VERBOSE=2
      python: 3.5
      script: tox
      after_success: codecov -e TOXENV
