edit_uri: tree/master/docs
extra_css:
  - https://assets.readthedocs.org/static/css/badge_only.css
  - https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
  - https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css
extra_javascript:
  - readthedocs-data.js
  - https://assets.readthedocs.org/static/core/js/readthedocs-doc-embed.js
  - https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js
markdown_extensions:
  - toc:
      permalink: True
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_unimoji:
      span_class: 'custom_emoji'
      emoji:
        '<img alt="rocket" src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png" width="30" height="30"/>': [ ':rocket:' ]
        '<img alt="construction" src="/images/emoji/construction.png" width="30" height="30"/>': [ ':construction:' ]
        '<img alt="warning" src="/images/emoji/warning.png" width="30" height="30"/>': [ ':warning:' ]
        '<img alt="baby_symbol" src="/images/emoji/baby_symbol.png" width="30" height="30"/>': [ ':baby_symbol:' ]
        '<img alt="information_source" src="/images/emoji/information_source.png" width="30" height="30"/>': [ ':information_source:' ]


repo_url: https://github.com/ezh/cloudselect
site_author: ezh
site_description: FZF selector for cloud instances
site_name: CloudSelect

theme:
  custom_dir: 'docs/theme/'
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json
    - python

nav:
  - Overview: index.md
  - Quick start: quick-start.md
  - FAQ: faq.md
  - Reference:
      - Overview: Reference/index.md
      - CloudSelect: Reference/cloudselect.md
      - Selector: Reference/selector.md
      - Discovery plugins: Reference/discovery.md
      - Group plugins: Reference/group.md
      - Pathfinder plugins: Reference/pathfinder.md
      - Report plugins: Reference/report.md
